---
- name: Debug
  ansible.builtin.debug:
    msg: Host {{ inventory_hostname }}.

- name: Copy monit httpd cfg
  ansible.builtin.copy:
    src: httpd.conf
    dest: /etc/monit/conf.d/httpd

- name: Pass monit configuration files
  ansible.builtin.template:
    src: monit.haproxy.conf.j2
    dest: /etc/monit/conf.d/haproxy
    owner: root
    group: root

- name: Enable monit service
  ansible.builtin.systemd:
    name: monit
    enabled: true
    masked: no

- name: Start monit service
  ansible.builtin.systemd:
    name: monit
    state: restarted
    daemon_reload: true
